package:
    name:           yii2-asset-octicons
    namespace:      hiqdev\assets\octicons
    label:          Yii2AssetOcticons
    title:          Yii2 asset for GitHub Octicons
    type:           yii2-extension
    keywords:       yii2, asset, octicons
    description:    Yii2 asset for https://octicons.github.com/

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
