package:
    name:           yii2-asset-octicons
    label:          Yii2AssetOcticons
    title:          Yii2 Asset Octicons
    type:           package
    keywords:       yii2, asset, octicons
    namespace:      hiqdev\yii2\assets\octicon
    year:           2015

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
