package:
    name:           yii2-asset-octicons
    label:          Yii2AssetOcticons
    title:          Yii2 Asset Octicons
    type:           yii2-extension
    keywords:       yii2, asset, octicons
    namespace:      hiqdev\assets\octicons
    year:           2015

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
